# Generated by Django 4.0.5 on 2022-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(max_length=50)),
                ('city_area', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('house_type', models.CharField(max_length=10)),
                ('house_square', models.CharField(max_length=20)),
                ('average_price', models.IntegerField()),
            ],
        ),
    ]
